export const ENTITIES_SYNC = 'ENTITIES_SYNC'
export const MACHINE_SYNC = 'MACHINE_SYNC'

export const ROUTES_FETCH = 'ROUTES_FETCH'
export const ROUTES_FETCH_FULFILLED = 'ROUTES_FETCH_FULFILLED'
export const ROUTES_FETCH_REJECTED = 'ROUTES_FETCH_REJECTED'

export const BUSES_POLLING_START = 'BUSES_POLLING_START'
